### ISSUE TITLE
Add Annotation

### ISSUE THREAD

**Issue by Vimbayinashe** [fredrik-philippe-vimbayi/auth-microservice#37]
- `@Service annotation` is required on service classes - **required**
-  `@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)` on config beans can improve our application's performance - **optional**

**Comment by Philippevial** [comment]
According to this link, Singleton scope is default if no other scope is defined.
https://www.baeldung.com/spring-bean-scopes

So i guess we don't need the @Scope annotation, but i'll add the @Service annotation to the service classes!
